version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file: .env
  web:
    tty: true
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
  redis:
    image: redis
    volumes:
      - redis_data:/redis_data
  celery:
    build: .
    volumes:
      - .:/app
    command: celery -A petshop worker -l INFO
    depends_on:
      - redis
    env_file: .env

volumes:
  redis_data: