# Generated by Django 4.0.3 on 2022-05-28 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_classification_alter_animal_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.classification', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Описание'),
        ),
    ]
