# Generated by Django 4.0.3 on 2022-05-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_animal_classification_alter_animal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='seller_number',
            field=models.TextField(default=375290000000, max_length=13, verbose_name='Номер продавца'),
            preserve_default=False,
        ),
    ]
